// The how-to video's script: one ordered list of timed events, read by
// guide.html (picture) and sfx.mjs (sound) so the two can never drift apart.
// Bot messages are referenced by capture step + reply index (assets/bot.json),
// so every bot text on screen is the real one.
//
// Classic script (file:// pages cannot import modules) and valid ESM for Node.
globalThis.TL = {
  duration: 60,
  steps: ['Boshlash', 'Xarajat yozish', 'Qarzlar', 'Hisobotlar', 'Web panel'],
  events: [
    // ── Intro ────────────────────────────────────────────────────────────
    { t: 0.0, type: 'intro' },
    { t: 3.0, type: 'phone', mode: 'start' },

    // ── 1. Boshlash ─────────────────────────────────────────────────────
    { t: 3.4, type: 'caption', step: 1, text: 'Telegramda <b>@hamyonchai_bot</b> ni oching va <b>START</b> ni bosing' },
    { t: 4.6, type: 'tap', target: { start: true } },
    { t: 4.8, type: 'phone', mode: 'chat' },
    { t: 4.8, type: 'send', id: 'u-start', text: '/start' },
    { t: 5.3, type: 'bot', id: 'welcome', from: ['start', 0] },
    { t: 6.0, type: 'caption', text: 'Tilni va valyutani tanlang' },
    { t: 6.6, type: 'tap', target: { msg: 'welcome', btn: "O'zbekcha" } },
    { t: 6.9, type: 'edit', id: 'welcome', from: ['lang', 0] },
    { t: 7.9, type: 'tap', target: { msg: 'welcome', btn: "So'm (UZS)" } },
    { t: 8.2, type: 'edit', id: 'welcome', from: ['currency', 0] },
    { t: 8.8, type: 'caption', text: 'Birinchi xarajatni oddiy so‘z bilan yozing' },
    { t: 9.0, type: 'type', end: 9.9, text: 'taksi 25 ming' },
    { t: 10.0, type: 'send', id: 'u-taxi', text: 'taksi 25 ming' },
    { t: 10.5, type: 'bot', id: 'taxi', from: ['taxi', 0] },
    { t: 11.0, type: 'bot', id: 'remind', from: ['taxi', 1] },
    { t: 11.4, type: 'caption', text: 'Kunlik eslatma vaqtini tanlang — tayyor!' },
    { t: 12.2, type: 'tap', target: { msg: 'remind', btn: '21:00' } },
    { t: 12.5, type: 'edit', id: 'remind', from: ['reminder', 0] },
    { t: 13.0, type: 'bot', id: 'menu', from: ['reminder', 1] },
    { t: 13.0, type: 'kb', show: true },

    // ── 2. Xarajat yozish ───────────────────────────────────────────────
    { t: 14.0, type: 'caption', step: 2, text: 'Kategoriya noto‘g‘ri bo‘lsa — <b>tugmasini bosing</b>' },
    { t: 14.0, type: 'kb', show: false },
    { t: 14.1, type: 'scroll', end: 14.6, target: 'taxi' },
    { t: 14.9, type: 'tap', target: { msg: 'taxi', btn: '🚕 Transport' } },
    { t: 15.2, type: 'edit', id: 'taxi', from: ['category', 0] },
    { t: 16.4, type: 'tap', target: { msg: 'taxi', btn: '🚕 Transport', last: true } },
    { t: 16.7, type: 'edit', id: 'taxi', from: ['taxi', 0] },
    { t: 16.9, type: 'scroll', end: 17.3, target: null },
    { t: 17.5, type: 'caption', text: 'Bitta xabarda bir nechta xarajat ham bo‘ladi' },
    { t: 17.7, type: 'type', end: 18.6, text: 'non 5 ming, sut 12 ming' },
    { t: 18.7, type: 'send', id: 'u-multi', text: 'non 5 ming, sut 12 ming' },
    { t: 19.1, type: 'bot', id: 'non', from: ['multi', 0] },
    { t: 19.4, type: 'bot', id: 'sut', from: ['multi', 1] },
    { t: 20.0, type: 'caption', text: 'Daromad ham xuddi shunday yoziladi' },
    { t: 20.2, type: 'type', end: 20.9, text: 'oylik tushdi 6 mln' },
    { t: 21.0, type: 'send', id: 'u-income', text: 'oylik tushdi 6 mln' },
    { t: 21.4, type: 'bot', id: 'income', from: ['income', 0] },
    { t: 21.8, type: 'caption', text: 'Xato bo‘lsa — <b>🗑 O‘chirish</b> tugmasi' },
    { t: 21.9, type: 'hl', end: 22.8, target: { msg: 'income', btn: "🗑 O'chirish" } },

    // ── 3. Qarzlar ──────────────────────────────────────────────────────
    { t: 23.0, type: 'caption', step: 3, text: 'Qarz berdingizmi yoki oldingizmi — shunchaki yozing' },
    { t: 23.2, type: 'type', end: 24.4, text: 'Alisherga 200 ming qarz berdim' },
    { t: 24.5, type: 'send', id: 'u-debt', text: 'Alisherga 200 ming qarz berdim' },
    { t: 25.0, type: 'bot', id: 'debt', from: ['debt', 0] },
    { t: 25.7, type: 'caption', text: 'Qarz xarajat emas — <b>alohida</b> hisoblanadi' },
    { t: 26.6, type: 'caption', text: '<b>📅 Muddat</b> qo‘ysangiz — vaqtida eslatadi' },
    { t: 26.7, type: 'hl', end: 27.9, target: { msg: 'debt', btn: '📅 Muddat' } },

    // ── 4. Hisobotlar ───────────────────────────────────────────────────
    { t: 28.2, type: 'caption', step: 4, text: 'Hisobotlar — pastdagi <b>menyu tugmalarida</b>' },
    { t: 28.2, type: 'kb', show: true },
    { t: 29.0, type: 'tap', target: { kb: '📊 Bugun' } },
    { t: 29.2, type: 'send', id: 'u-today', text: '📊 Bugun' },
    { t: 29.7, type: 'bot', id: 'today', from: ['today', 0], countUp: true },
    { t: 31.0, type: 'caption', text: 'Hafta va oy hisoboti ham bir bosishda' },
    { t: 31.1, type: 'hl', end: 32.0, target: { kb: '📅 Hafta' } },
    { t: 31.5, type: 'hl', end: 32.4, target: { kb: '🗓 Oy' } },
    { t: 32.3, type: 'caption', text: 'Limit, qarz, maqsad — hammasi menyuda' },
    { t: 32.4, type: 'hl', end: 33.5, target: { kb: '🎯 Limitlar' } },
    { t: 32.6, type: 'hl', end: 33.5, target: { kb: '🤝 Qarzlar' } },
    { t: 32.8, type: 'hl', end: 33.5, target: { kb: '🏦 Maqsadlar' } },

    // ── 5. Web panel ────────────────────────────────────────────────────
    { t: 33.8, type: 'caption', step: 5, text: '<b>🌐 Web panel</b> tugmasini bosing' },
    { t: 34.5, type: 'tap', target: { kb: '🌐 Web panel' } },
    { t: 34.7, type: 'send', id: 'u-web', text: '🌐 Web panel' },
    { t: 35.2, type: 'bot', id: 'web', from: ['web', 0], button: 'Web panelni ochish ↗' },
    { t: 35.9, type: 'caption', text: 'Havola <b>15 daqiqa</b> amal qiladi va bir marta ishlaydi' },
    { t: 37.0, type: 'tap', target: { msg: 'web', btn: 'Web panelni ochish ↗' } },
    { t: 37.3, type: 'phone', mode: 'web', page: 'dashboard', nav: 1 },
    { t: 37.9, type: 'caption', text: 'Balans, xarajat va daromad — bir qarashda' },
    { t: 39.4, type: 'caption', text: 'Pul qayerga ketayotgani — kategoriyalar bo‘yicha' },
    { t: 39.4, type: 'wscroll', end: 41.0, to: 470 },
    { t: 41.6, type: 'tap', target: { web: 'nav2' } },
    { t: 41.8, type: 'page', page: 'records', nav: 2 },
    { t: 41.9, type: 'caption', text: 'Yozuvlar: qidirish, filtr va tahrirlash' },
    { t: 42.4, type: 'hl', end: 43.2, target: { web: 'search' } },
    { t: 43.5, type: 'tap', target: { web: 'fab' } },
    { t: 43.7, type: 'sheet', page: 'record-add' },
    { t: 43.8, type: 'caption', text: '<b>＋</b> tugmasi — qo‘lda yozuv qo‘shish' },
    { t: 45.1, type: 'sheet', page: null },
    { t: 45.5, type: 'tap', target: { web: 'nav3' } },
    { t: 45.7, type: 'page', page: 'debts', nav: 3 },
    { t: 45.8, type: 'caption', text: 'Qarzlar: kim, qancha va qachon qaytaradi' },
    { t: 46.9, type: 'tap', target: { web: 'fabDebt' } },
    { t: 47.1, type: 'sheet', page: 'debt-add' },
    { t: 47.2, type: 'caption', text: 'Muddat va <b>@username</b> — qarzdorga ham eslatma boradi' },
    { t: 47.8, type: 'hl', end: 49.0, target: { web: 'duser' } },
    { t: 49.2, type: 'sheet', page: null },
    { t: 49.5, type: 'tap', target: { web: 'nav4' } },
    { t: 49.7, type: 'page', page: 'settings', nav: 4 },
    { t: 49.8, type: 'caption', text: 'Sozlamalar: til, eslatma vaqti, kategoriyalar' },
    { t: 50.3, type: 'wscroll', end: 51.4, to: 380 },

    // ── Tips + outro ────────────────────────────────────────────────────
    { t: 52.0, type: 'tips' },
    { t: 57.2, type: 'outro' },
  ],
};
